### ISSUE TITLE
[12345]投诉垃圾收集点设置数量不足、分布不合理、分类形同虚设-20190628016688

### ISSUE THREAD

**Issue by wangxiaowang104** [forthehome/forthehome#7]
20190628下午1：30向12345投诉主题事项，回复转至相关部门处理。
20190628下午2：43街道居委会书记王萍打来电话，声称小区设置了8个垃圾收集点，分布合理，后续物业会有大型设备收集处理垃圾。回复她，垃圾收集点设置够不够、合不合理，我要看后续实际情况，目前情况就是不合理、不够、无法正常按规则分类扔垃圾。王萍未做回复。
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9904.JPG)

**Comment by forthehome** [comment]
2019年6月30日的图像记录
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9880.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9881.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9882.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9883.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9884.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9885.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9886.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9887.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9888.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9889.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9891.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9892.JPG)

**Comment by forthehome** [comment]
2019年7月1日的图像记录
Note·：·
7月1日上午垃圾处理能力已经基本瘫痪
7月1日下午开始新投放60个垃圾桶，7月2日继续观察效果
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9912.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9912.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9912.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9912.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9912.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9912.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9912.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9912.JPG)

**Comment by forthehome** [comment]
2019年7月2日的图像记录
在增加了60个垃圾桶和2个投放点后，投放点垃圾溢出的问题有改善，但仍然无法做到有效分类，特别是商户还存在随地乱丢的问题
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9939.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9940.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9941.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9942.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9943.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9944.JPG)

**Comment by forthehome** [comment]
2019年7月3日的图像记录
可以看到在增加了60个垃圾桶和2个投放点后，总容量依然是不够进行垃圾分类的。
虽然午后物业清理了步行街的垃圾，但商贩露天随意丢弃垃圾的行为依旧没有得到行政处罚，城管在新凯地区的描边式执法（不进小区）只是用来做新闻的吗？
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9945.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9946.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9947.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9948.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9949.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9950.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9951.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9952.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9964.JPG)
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9965.JPG)

**Comment by forthehome** [comment]
2019年7月4日
并无进一步的改善，下一次图片更新预定在7月7日

**Comment by forthehome** [comment]
2019年7月7日的图像记录
依然无法正常分类，部分投放点仍然有垃圾溢出的情况。鉴于状态已经连续数日没有任何改变，更新周期改为周更。
![avatar](https://raw.githubusercontent.com/forthehome/forthehome/master/public/images/IMG_9994.JPG)

**Comment by forthehome** [comment]
长期未得到确认，暂时关闭
