### ISSUE TITLE
7月9日向松江区纪检委举报贾银根不作为乱作为查询码—BFGC6479I5DI8NEFNJMR，BFG264I1D75FID232HTF，BF62G4835506D3JA119K，156264I4F85J794O719G

### ISSUE THREAD

**Issue by wangxiaowang104** [forthehome/forthehome#9]
7月9日向松江区纪检委举报贾银根不作为乱作为
全文如下：

[关于贾银根担任上海市松江区泗泾街道新凯家园一期小区第三届业主委员会主任的不作为、乱作为的问题DOCX.docx](https://github.com/forthehome/forthehome/files/3375722/DOCX.docx)

**Comment by forthehome** [comment]
长期未得到确认，暂时关闭
